// Code generated by "stringer -type ClientMsgType messages.go"; DO NOT EDIT.

package messages

import "fmt"

const _ClientMsgType_name = "CMUnknownCMSubscribeCMDropCMSendText"

var _ClientMsgType_index = [...]uint8{0, 9, 20, 26, 36}

func (i ClientMsgType) String() string {
	if i < 0 || i >= ClientMsgType(len(_ClientMsgType_index)-1) {
		return fmt.Sprintf("ClientMsgType(%d)", i)
	}
	return _ClientMsgType_name[_ClientMsgType_index[i]:_ClientMsgType_index[i+1]]
}
