// Code generated by "stringer -type ServerMsgType messages.go"; DO NOT EDIT.

package messages

import "fmt"

const _ServerMsgType_name = "SMUnknownSMError"

var _ServerMsgType_index = [...]uint8{0, 9, 16}

func (i ServerMsgType) String() string {
	if i < 0 || i >= ServerMsgType(len(_ServerMsgType_index)-1) {
		return fmt.Sprintf("ServerMsgType(%d)", i)
	}
	return _ServerMsgType_name[_ServerMsgType_index[i]:_ServerMsgType_index[i+1]]
}
